### ISSUE TITLE
Week 1 - Ava

### ISSUE THREAD

**Issue by avabrooks** [ridhimainukurti/p1-Valid#11]
- [x] Create [wire frames](https://github.com/ridhimainukurti/p1-Valid/wiki/Templating-Guide)
- [x] Implement [sassy ](https://sass-lang.com/install)
- [x] Start design 
  - [x] Primary and secondary colors 
    - [x] Blues and Greens: similar to Del Norte colors

**Comment by PrishaMaiti** [comment]
Design Manager (Ava) - Updated the README just a few minutes ago
