### ISSUE TITLE
Week 1- Sarah

### ISSUE THREAD

**Issue by sarahwxie** [ridhimainukurti/p1-Valid#14]
- [x] [Brainstorm](https://github.com/ridhimainukurti/p1-Valid/wiki/Brainwrite) applications of search feature
- [x] Add Search Feature to [Project Plan](https://github.com/ridhimainukurti/p1-Valid/wiki/Project-Plan)
- [x]  Create person searching in the [model](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/java/com/nighthawk/csa/data/SQL/PersonJpaRepository.java)
- [x] Add the search page to the [controller](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/java/com/nighthawk/csa/data/SQL/PersonSqlRepository.java)
- [x] Create Search [View](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/resources/templates/data/person_search.html)

**Comment by PrishaMaiti** [comment]
Technical Officer (Sarah) - Updated the MVC for Search Feature
