### ISSUE TITLE
Week 2 Review Ticket

### ISSUE THREAD

**Issue by ridhimainukurti** [ridhimainukurti/p1-Valid#19]
- [x] [Deployed Web Site](https://github.com/ridhimainukurti/p1-Valid/projects/1#card-74287890) 
- [x] About Pages
     - [x] page layout with customization (theme, colors, font) 
     - [x] option toggle between picture with mask & picture without mask (hover feature or button) 
     - [x] pull or show web API information on individual about page 
     - [x] establish links to journal
     - [ ] store and receive data within a database 
            - [Ava](https://github.com/ridhimainukurti/p1-Valid/projects/1#card-74544407) , [Ridhima](https://github.com/ridhimainukurti/p1-Valid/issues/26#issue-1076848682) , [Risa](https://github.com/ridhimainukurti/p1-Valid/projects/1#card-74543510)
- [ ] TPT: Unit 2 FRQ deployed

**Comment by ridhimainukurti** [comment]
**Individual: Ridhima**
About Pages on deployed on Site
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Page must use a Layout and have special customization (color pallet, background, etc)
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Picture with Mask that toggles to Picture of Choice (ie pic without mask).  Perhaps ASCII art.
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Pull or show data (Web API) with information of interest
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Store and Retrieve Data
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Unit #2 FRQ deployed
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

**Comment by risaiwazaki** [comment]
**Individual: Risa**
About Pages on deployed on Site
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Page must use a Layout and have special customization (color pallet, background, etc)
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Picture with Mask that toggles to Picture of Choice (ie pic without mask).  Perhaps ASCII art.
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/blob/0dc40bf451445505f207a240d4cbba76fd12e244/src/main/resources/static/images/RisaMask.png)

Pull or show data (Web API) with information of interest
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/blob/aa9da44e757be3869e06a66303c8da863b4e0950/src/main/java/com/nighthawk/csa/MainController.java#L77-L91)

Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/blob/aa9da44e757be3869e06a66303c8da863b4e0950/src/main/resources/templates/individual/risa.html#L51)

Store and Retrieve Data
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: 

Unit #2 FRQ deployed
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification:

**Comment by avabrooks** [comment]
Individual: Ava
About Pages on deployed on Site

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: [link](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/resources/templates/individual/ava.html)
Page must use a Layout and have special customization (color pallet, background, etc)

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: [Bootstrap layout and customized gradient design](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/resources/templates/individual/ava.html)
Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: [Mask to Mort](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/resources/templates/individual/ava.html#L25-L42)
Pull or show data (Web API) with information of interest

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0
- [ ] Ju

Justification: Jokic API: [frontend ](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/resources/templates/individual/ava.html#L45-L66)+ [backend ](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/java/com/nighthawk/csa/data/AvaWebAPI.java#L22-L61)

Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: [link](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/resources/templates/individual/ava.html#L70-L76)
Store and Retrieve Data

- [ ]  1.0
- [ ]  .75
- [x]  .5
- [ ]  0

Justification: [API](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/java/com/nighthawk/csa/data/AvaWebAPI.java#L22-L61)
Unit #2 FRQ deployed

- [x]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification: [link](https://github.com/ridhimainukurti/p1-Valid/blob/master/src/main/resources/templates/individual/ava.html#L70-L76)

Total Individual Score: 6.5/7

**Comment by avabrooks** [comment]
**Team**
README quality, release day policies, Scrum Board to week after break

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification:
Team: Deployed Web Site

- [ ]  1.0
- [ ]  .75
- [ ]  .5
- [ ]  0

Justification:

**Comment by mistylavender** [comment]
**Individual: Natasha**
About Pages on deployed on Site

- [ ] 1.0
- [ ] .75
- [ ] .5
- [ ] 0
    Justification:

Page must use a Layout and have special customization (color pallet, background, etc)

    1.0
    .75
    .5
    0
    Justification:

Picture with Mask that toggles to Picture of Choice (ie pic without mask). Perhaps ASCII art.

    1.0
    .75
    .5
    0
    Justification:

Pull or show data (Web API) with information of interest

    1.0
    .75
    .5
    0
    Justification:

Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)

    1.0
    .75
    .5
    0
    Justification:

Store and Retrieve Data

    1.0
    .75
    .5
    0
    Justification:

Unit #2 FRQ deployed

    1.0
    .75
    .5
    0
    Justification:

Total Score: /7

**Comment by sarahwxie** [comment]
**Individual: Sarah**
About Pages on deployed on Site
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Page must use a Layout and have special customization (color pallet, background, etc)
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/issues/26)

Picture with Mask that toggles to Picture of Choice (ie pic without mask).  Perhaps ASCII art.
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/blob/0dc40bf451445505f207a240d4cbba76fd12e244/src/main/resources/static/images/RisaMask.png)

Pull or show data (Web API) with information of interest
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/blob/aa9da44e757be3869e06a66303c8da863b4e0950/src/main/java/com/nighthawk/csa/MainController.java#L77-L91)

Establish link(s) to journal and other key indicators of your work and progress on your home page (remember Tri 1 pop quiz)
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: [Code](https://github.com/ridhimainukurti/p1-Valid/blob/aa9da44e757be3869e06a66303c8da863b4e0950/src/main/resources/templates/individual/risa.html#L51)

Store and Retrieve Data
- [ ] 1.0
- [ ]  .75
- [ ] .5
- [x]  0
Justification: 

Unit #2 FRQ deployed
- [x] 1.0
- [ ]  .75
- [ ] .5
- [ ]  0
Justification: 

Total Score: /7
