### ISSUE TITLE
Risa & Rohan & Adi's FRQ Peer Grading

### ISSUE THREAD

**Issue by risaiwazaki** [ridhimainukurti/p1-Valid#39]
This is Risa & Rohan & Adi's FRQ

**Comment by risaiwazaki** [comment]
| Name | Tasks | Commits |
|  --- |  ---           | --- | 
| Natasha | | | 
| Ridhima | |  |
| Risa | [Ticket](https://github.com/ridhimainukurti/p1-Valid/projects/1#card-75655057) | [Commits](https://github.com/ridhimainukurti/p1-Valid/commits/master?before=8aa415c15cf294de000701b49f33f8a113c74d26+35&branch=master) |
| Ava | [Ticket](https://github.com/ridhimainukurti/p1-Valid/projects/1#card-74549540) |[Commits]() | 
| Sarah |  | [Commits](https://github.com/ridhimainukurti/p1-Valid/commits?author=sarahwxie) |

**Comment by risaiwazaki** [comment]
**RISA GRADING**

| Feature | Evaluation | Score | Grader |
|  --- |  ---           | --- | ---|
| Each individual has GitHub Page, Wiki, or deployed Web Page that Highlights talking points and learnings from each FRQ | | | Rohan|
| Each Individual has their own set of FRQs running under one page or menu (ie Deployed Java/Spring or Replit) | |  | Rohan|
| Each Individual has GitHub of source for every FRQ that is integrated with Deployed Java/Spring or Replit | |  | Rohan|
| At least 2 FRQs with input and output | | | Risa|

**Comment by risaiwazaki** [comment]
**ADI GRADING**

| Feature | Evaluation | Score | Grader |
|  --- |  ---           | --- | ---|
| Each individual has GitHub Page, Wiki, or deployed Web Page that Highlights talking points and learnings from each FRQ | | | Rohan|
| Each Individual has their own set of FRQs running under one page or menu (ie Deployed Java/Spring or Replit) | |  | Rohan|
| Each Individual has GitHub of source for every FRQ that is integrated with Deployed Java/Spring or Replit | |  | Rohan|
| At least 2 FRQs with input and output | | | Rohan|

**Comment by risaiwazaki** [comment]
# Frq Comparison and Reflection
- General Reflection : (Provide a summary reflection on your FRQs, your weaknesses, and your strengths.)
| Adi FRQs     | Rohan FRQs   | Risa FRQs  | Comparison |
| ----------- | ----------- | ----------- | ----------- |
| Frq #      | Frq #     | Title       |
| Frq #     | Frq #      | Title       |
| Frq #     | Frq #       | Title       |

**Comment by adhithin** [comment]
Feature | Evaluation | Score | Grader
-- | -- | -- | --
Each individual has GitHub Page, Wiki, or deployed Web Page that Highlights talking points and learnings from each FRQ |   [Yes](https://github.com/ridhimainukurti/p1-Valid/wiki/Risa's-FRQ-Understanding) |  2.75/3 | Adi
Each Individual has their own set of FRQs running under one page or menu (ie Deployed Java/Spring or Replit) |  [Yes]()  |   | Adi
Each Individual has GitHub of source for every FRQ that is integrated with Deployed Java/Spring or Replit |   |   | Adi
At least 2 FRQs with input and output |   |   | Adi
