### ISSUE TITLE
Week 1 Goals

### ISSUE THREAD

**Issue by avabrooks** [ridhimainukurti/p1-Valid#4]
- [x] Design: [Brainwrite](https://github.com/ridhimainukurti/p1-Valid/wiki/Brainwrite) & [Wireframe](https://github.com/ridhimainukurti/p1-Valid/wiki/Wire-Frames)
- [x] Technical: [10-12 key ideas](https://github.com/ridhimainukurti/p1-Valid/wiki/Technicals-Ideas)
- [x] Github: [Contributing Guidelines](https://github.com/ridhimainukurti/p1-Valid/wiki/Contributing-Guidelines) 
- [x] Deployment: [Deployment Guide](https://github.com/ridhimainukurti/p1-Valid/wiki/Deployment-Guide)
- [x] Scrum Board: Assignments & [Backlog](https://github.com/ridhimainukurti/p1-Valid/projects/1#column-17059525)

**Comment by chenxin-chex** [comment]
Deployment has guide for other members and frequency of updating, but schedule should be timeboxed or bolded - .9/1

**Comment by PrishaMaiti** [comment]
The brain write is really organized and I could clearly see how you organized your thoughts and ultimately led to the idea of a tutoring site: 1/1. I don't see the wireframe: 0/1. 1/1 for the Wiki Theme.

**Comment by rkwreck** [comment]
- technical ideas 1/1 
- Github Wiki specifies management plan and push/pull policies 1/1 
- Scrum Board has all issues and organized columns 1/1

**Comment by rkwreck** [comment]
Individual scores:
Natasha - Completed assigned tasks in issues. Scrum Wiki page is incomplete. 
Ridhima - Completed assigned tasks in issues. Github page is complete.
